# Generated by Django 5.2.7 on 2025-10-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('pagamento_em_dia', models.BooleanField(default=True)),
                ('queixa', models.TextField(choices=[('Cefaleia', 'Cefaleia'), ('Tontura', 'Tontura'), ('Convulsão', 'Convulsão'), ('Perda de consciência', 'Perda de consciência'), ('Fraqueza muscular', 'Fraqueza muscular'), ('Dormência ou formigamento', 'Dormência ou formigamento'), ('Problemas de memória', 'Problemas de memória'), ('Alterações de humor', 'Alterações de humor'), ('Dificuldade de concentração', 'Dificuldade de concentração'), ('Distúrbios do sono', 'Distúrbios do sono'), ('Outro', 'Outro')], max_length=500)),
            ],
        ),
    ]
