# Generated by Django 5.2.7 on 2025-10-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=100)),
                ('instrucoes', models.TextField(max_length=500)),
                ('frequencia', models.CharField(choices=[('D', 'Diária'), ('S', 'Semanal'), ('M', 'Mensal'), ('15', '1 vez por semana'), ('25', '2 vez por mês'), ('35', '3 vez por mês'), ('N', 'Ao necessário'), ('O', 'Outro')], default='D', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='queixa',
            field=models.TextField(choices=[('Déficit de atenção', 'Déficit de atenção'), ('Hiperatividade', 'Hiperatividade'), ('Impulsividade', 'Impulsividade'), ('Ansiedade', 'Ansiedade'), ('Depressão', 'Depressão'), ('Cefaleia', 'Cefaleia'), ('Tontura', 'Tontura'), ('Convulsão', 'Convulsão'), ('Perda de consciência', 'Perda de consciência'), ('Fraqueza muscular', 'Fraqueza muscular'), ('Dormência ou formigamento', 'Dormência ou formigamento'), ('Problemas de memória', 'Problemas de memória'), ('Alterações de humor', 'Alterações de humor'), ('Dificuldade de concentração', 'Dificuldade de concentração'), ('Distúrbios do sono', 'Distúrbios do sono'), ('Outro', 'Outro')], max_length=500),
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(auto_now_add=True)),
                ('humor', models.IntegerField()),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
            ],
        ),
    ]
