# Generated by Django 5.2.7 on 2025-10-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_tarefas_alter_pacientes_queixa_consultas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='data_consulta',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='consultas',
            old_name='observacoes',
            new_name='registro_geral',
        ),
        migrations.AddField(
            model_name='consultas',
            name='tarefas',
            field=models.ManyToManyField(blank=True, to='pacientes.tarefas'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
